#!/usr/bin/env bash

COMMAND=$1

createDb () {
  docker exec api_web_1 rake db:create
}

migrateDb () {
  docker exec api_web_1 rake db:migrate
}

dropDb () {
  docker exec -e DISABLE_DATABASE_ENVIRONMENT_CHECK=1 api_web_1 rake db:drop
}

seedDb () {
  docker exec api_web_1 rake db:seed
}

testPrepare () {
  docker exec api_web_1 rake db:test:prepare
}

deleteDbVolume () {
  docker volume remove api_tinysis_data
}

shell () {
  docker exec -it api_web_1 bash
} 

server () {
  docker exec -it api_web_1 rm -rf /api/tmp/pids/server.pid && rails s
}

initDb () {
  dropDb
  createDb
  migrateDb
  seedDb
  testPrepare
}

reset () {
  stopContainers
  removeContainers
  removeImages
}

stopContainers () {
  docker stop api_web_1
  docker stop api_db_1
}

removeContainers () {
  docker rm api_web_1
  docker rm api_db_1
}

removeImages () {
  docker rmi api_web
  docker rmi api_db
}

# if this is not working, you need to get your AWS profile set up in 
# ~/.aws/credentials. Contact artzt@juniperswordplay.com for access.
#
getSecrets () {
  aws s3 cp --profile=tinysis-devtest s3://tinysis-devtest/api . --recursive
}

build () {
  docker-compose up
}

log () {
  docker exec -it api_web_1 tail -f log/*
}

usage () {
  echo "tiny-utils <command>"
  echo ""
  echo "Commands:"
  echo "---------"
  echo "getSecrets | generally one-time S3 download of any dev secrets files - requires AWS profile and access key"
  echo "build      | applies docker-compose to start the API stack"
  echo "initDb     | sets up the development database; will delete the existing data if it exists"
  echo "server     | starts the development server"
  echo "shell      | opens a bash shell on the Rails API container"
  echo "log        | tail the production log"
  echo "reset      | deletes the docker images for the API and DB"
}

case "$COMMAND" in
  "getSecrets"|"initDb"|"build"|"server"|"shell"|"log"|"reset")
      $COMMAND
      ;;
  *)
      usage
esac