#!/usr/bin/env bash

COMMAND=$1
WEB=tiny_web_1

createDb () {
  docker exec $WEB rake db:create
}

migrateDb () {
  docker exec $WEB rake db:migrate
}

dropDb () {
  docker exec -e DISABLE_DATABASE_ENVIRONMENT_CHECK=1 $WEB rake db:drop
}

seedDb () {
  docker exec $WEB rake db:seed
}

testPrepare () {
  docker exec $WEB rake db:test:prepare
}

deleteDbVolume () {
  docker volume remove tiny_tinysis_data
}

shell () {
  docker exec -it $WEB bash
} 

server () {
  docker exec -it $WEB rm -rf /api/tmp/pids/server.pid && rails s
}

initDb () {
  dropDb
  createDb
  migrateDb
  seedDb
  testPrepare
}

reset () {
  stopContainers
  removeContainers
  removeImages
}

stopContainers () {
  docker stop $WEB
  docker stop $DB
  docker stop $ADMINER
}

removeContainers () {
  docker rm $WEB
  docker rm $DB
}

removeImages () {
  docker rmi tiny_web
  docker rmi tiny_db
}

# if this is not working, you need to get your AWS profile set up in 
# ~/.aws/credentials. Contact artzt@juniperswordplay.com for access.
#
getSecrets () {
  aws s3 cp --profile=tinysis-devtest s3://tinysis-devtest/api . --recursive
}

build () {
  docker-compose up
}

log () {
  docker exec -it $WEB tail -f log/*
}

test:api () {
  docker exec -e RAILS_ENV=test $WEB bundle exec rspec
}

usage () {
  echo "tiny <command>"
  echo ""
  echo "Commands:"
  echo "---------"
  echo "getSecrets | generally one-time S3 download of any dev secrets files - requires AWS profile and access key"
  echo "build      | applies docker-compose to start the API stack"
  echo "initDb     | sets up the development database; will delete the existing data if it exists"
  echo "server     | starts the development server"
  echo "shell      | opens a bash shell on the Rails API container"
  echo "log        | tail the production log"
  echo "reset      | deletes the docker images for the API and DB"
  echo "test:api   | runs test suite for API"
}

case "$COMMAND" in
  "getSecrets"|"initDb"|"build"|"server"|"shell"|"log"|"reset"|"test:api")
      $COMMAND
      ;;
  *)
      usage
esac