FROM ruby:2.6.3

ENV LANG C.UTF-8

RUN apt-get update -qq
RUN apt-get install -y build-essential vim

ENV API_HOME /api
RUN mkdir -p $API_HOME
WORKDIR $API_HOME

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000
